services:
  dvor-chatbot:
    container_name: dvor-chatbot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./data:/app/data
